;;;
;;; Machine Generated By /bisos/git/auth/bxRepos/bisos/bsip4/bin/doomPkgsProfile.sh::vis_doomPkgsStdout on 20220528223625
;;; Input= /bisos/blee/29f/doom-main-blee3/.local/straight/repos
(
 (adaptive-wrap
  :repoUrl "https://github.com/emacs-straight/adaptive-wrap.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (add-node-modules-path
  :repoUrl "https://github.com/codesuki/add-node-modules-path.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (a.el
  :repoUrl "https://github.com/plexus/a.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (alert
  :repoUrl "https://github.com/jwiegley/alert.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (all-the-icons.el
  :repoUrl "https://github.com/domtronn/all-the-icons.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (anaconda-mode
  :repoUrl "https://github.com/pythonic-emacs/anaconda-mode.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (anzu
  :repoUrl "https://github.com/emacsorphanage/anzu.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (auctex
  :repoUrl "https://github.com/emacs-straight/auctex.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (auto-minor-mode
  :repoUrl "https://github.com/joewreschnig/auto-minor-mode.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (auto-yasnippet
  :repoUrl "https://github.com/abo-abo/auto-yasnippet.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (avy
  :repoUrl "https://github.com/abo-abo/avy.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (bbdb
  :repoUrl "https://git.savannah.nongnu.org/git/bbdb.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (bbdb-ext
  :repoUrl "https://github.com/vapniks/bbdb-ext.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (better-jumper
  :repoUrl "https://github.com/gilbertw1/better-jumper.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (biblio.el
  :repoUrl "https://github.com/cpitclaudel/biblio.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (browse-at-remote
  :repoUrl "https://github.com/rmuslimov/browse-at-remote.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (centaur-tabs
  :repoUrl "https://github.com/ema2159/centaur-tabs.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (citeproc-el
  :repoUrl "https://github.com/andras-simonyi/citeproc-el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (cmake-mode
  :repoUrl "https://github.com/emacsmirror/cmake-mode.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (company-anaconda
  :repoUrl "https://github.com/pythonic-emacs/company-anaconda.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (company-auctex
  :repoUrl "https://github.com/alexeyr/company-auctex.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (company-glsl
  :repoUrl "https://github.com/Kaali/company-glsl.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (company-irony
  :repoUrl "https://github.com/Sarcasm/company-irony.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (company-irony-c-headers
  :repoUrl "https://github.com/hotpxl/company-irony-c-headers.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (company-math
  :repoUrl "https://github.com/vspinu/company-math.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (company-mode
  :repoUrl "https://github.com/company-mode/company-mode.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (company-reftex
  :repoUrl "https://github.com/TheBB/company-reftex.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (company-shell
  :repoUrl "https://github.com/Alexander-Miller/company-shell.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (compat
  :repoUrl "https://github.com/emacs-straight/compat.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (consult
  :repoUrl "https://github.com/minad/consult.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (consult-flycheck
  :repoUrl "https://github.com/minad/consult-flycheck.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (consult-lsp
  :repoUrl "https://github.com/gagbo/consult-lsp.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (cuda-mode
  :repoUrl "https://github.com/chachi/cuda-mode.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (dash.el
  :repoUrl "https://github.com/magnars/dash.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (demangle-mode
  :repoUrl "https://github.com/liblit/demangle-mode.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (diff-hl
  :repoUrl "https://github.com/dgutov/diff-hl.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (diredfl
  :repoUrl "https://github.com/purcell/diredfl.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (dired-git-info
  :repoUrl "https://github.com/emacs-straight/dired-git-info.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (dired-rsync
  :repoUrl "https://github.com/stsquad/dired-rsync.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (disaster
  :repoUrl "https://github.com/jart/disaster.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (doom-modeline
  :repoUrl "https://github.com/seagle0128/doom-modeline.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (doom-snippets
  :repoUrl "https://github.com/hlissner/doom-snippets.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (drag-stuff.el
  :repoUrl "https://github.com/rejeep/drag-stuff.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (dtrt-indent
  :repoUrl "https://github.com/jscheid/dtrt-indent.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (dumb-jump
  :repoUrl "https://github.com/jacktasia/dumb-jump.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (eaf
  :repoUrl "https://github.com/emacsmirror/eaf.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (edit-indirect
  :repoUrl "https://github.com/Fanael/edit-indirect.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (el-get
  :repoUrl "https://github.com/dimitri/el-get.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (elisp-def
  :repoUrl "https://github.com/Wilfred/elisp-def.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (elisp-demos
  :repoUrl "https://github.com/xuchunyang/elisp-demos.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (elisp-refs
  :repoUrl "https://github.com/Wilfred/elisp-refs.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (elpy
  :repoUrl "https://github.com/jorgenschaefer/elpy.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (emacs-async
  :repoUrl "https://github.com/jwiegley/emacs-async.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (emacs-buttercup
  :repoUrl "https://github.com/jorgenschaefer/emacs-buttercup.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (emacs-calfw
  :repoUrl "https://github.com/kiwanami/emacs-calfw.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (emacs-company-dict
  :repoUrl "https://github.com/hlissner/emacs-company-dict.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (emacs-ctable
  :repoUrl "https://github.com/kiwanami/emacs-ctable.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (emacs-deferred
  :repoUrl "https://github.com/kiwanami/emacs-deferred.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (emacs-epc
  :repoUrl "https://github.com/kiwanami/emacs-epc.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (emacs-gif-screencast
  :repoUrl "https://gitlab.com/Ambrevar/emacs-gif-screencast.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (emacs-hide-mode-line
  :repoUrl "https://github.com/hlissner/emacs-hide-mode-line.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (emacs-htmlize
  :repoUrl "https://github.com/hniksic/emacs-htmlize.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (emacsmirror-mirror
  :repoUrl "https://github.com/emacs-straight/emacsmirror-mirror.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (emacs-python-pytest
  :repoUrl "https://github.com/wbolster/emacs-python-pytest.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (emacs-request
  :repoUrl "https://github.com/tkf/emacs-request.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (emacs-undo-fu
  :repoUrl "https://codeberg.org/ideasman42/emacs-undo-fu.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (emacs-undo-fu-session
  :repoUrl "https://codeberg.org/ideasman42/emacs-undo-fu-session.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (emacs-web-server
  :repoUrl "https://github.com/skeeto/emacs-web-server.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (Emacs-wgrep
  :repoUrl "https://github.com/mhayashi1120/Emacs-wgrep.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (emacs-which-key
  :repoUrl "https://github.com/justbur/emacs-which-key.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (embark
  :repoUrl "https://github.com/oantolin/embark.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (emms
  :repoUrl "https://git.savannah.gnu.org/git/emms.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (engine-mode
  :repoUrl "https://github.com/hrs/engine-mode.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (epl
  :repoUrl "https://github.com/cask/epl.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (eros
  :repoUrl "https://github.com/xiongtx/eros.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (expand-region.el
  :repoUrl "https://github.com/magnars/expand-region.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (explain-pause-mode
  :repoUrl "https://github.com/lastquestion/explain-pause-mode.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (fd-dired
  :repoUrl "https://github.com/yqrashawn/fd-dired.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (f.el
  :repoUrl "https://github.com/rejeep/f.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (flycheck
  :repoUrl "https://github.com/flycheck/flycheck.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (flycheck-cask
  :repoUrl "https://github.com/flycheck/flycheck-cask.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (flycheck-irony
  :repoUrl "https://github.com/Sarcasm/flycheck-irony.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (flycheck-package
  :repoUrl "https://github.com/purcell/flycheck-package.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (flycheck-popup-tip
  :repoUrl "https://github.com/flycheck/flycheck-popup-tip.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (fringe-helper.el
  :repoUrl "https://github.com/nschum/fringe-helper.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (gcmh
  :repoUrl "https://gitlab.com/koral/gcmh.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (general.el
  :repoUrl "https://github.com/noctuid/general.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (ghub
  :repoUrl "https://github.com/magit/ghub.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (git-gutter
  :repoUrl "https://github.com/emacsorphanage/git-gutter.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (git-gutter-fringe
  :repoUrl "https://github.com/emacsorphanage/git-gutter-fringe.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (github-review
  :repoUrl "https://github.com/charignon/github-review.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (git-modes
  :repoUrl "https://github.com/magit/git-modes.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (git-timemachine
  :repoUrl "https://gitlab.com/pidu/git-timemachine.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (glsl-mode
  :repoUrl "https://github.com/jimhourihan/glsl-mode.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (gntp.el
  :repoUrl "https://github.com/tekai/gntp.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (gnu-elpa-mirror
  :repoUrl "https://github.com/emacs-straight/gnu-elpa-mirror.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (guess-language.el
  :repoUrl "https://github.com/tmalsburg/guess-language.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (helm-bibtex
  :repoUrl "https://github.com/tmalsburg/helm-bibtex.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (helpful
  :repoUrl "https://github.com/Wilfred/helpful.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (Highlight-Indentation-for-Emacs
  :repoUrl "https://github.com/antonj/Highlight-Indentation-for-Emacs.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (highlight-indent-guides
  :repoUrl "https://github.com/DarthFennec/highlight-indent-guides.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (highlight-numbers
  :repoUrl "https://github.com/Fanael/highlight-numbers.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (highlight-quoted
  :repoUrl "https://github.com/Fanael/highlight-quoted.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (hl-todo
  :repoUrl "https://github.com/tarsius/hl-todo.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (ht.el
  :repoUrl "https://github.com/Wilfred/ht.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (hydra
  :repoUrl "https://github.com/abo-abo/hydra.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (irony-eldoc
  :repoUrl "https://github.com/ikirill/irony-eldoc.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (irony-mode
  :repoUrl "https://github.com/Sarcasm/irony-mode.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (jekyll-modes
  :repoUrl "https://github.com/fred-o/jekyll-modes.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (js2-mode
  :repoUrl "https://github.com/mooz/js2-mode.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (js2-refactor.el
  :repoUrl "https://github.com/js-emacs/js2-refactor.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (json-mode
  :repoUrl "https://github.com/joshwnj/json-mode.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (json-reformat
  :repoUrl "https://github.com/gongo/json-reformat.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (json-snatcher
  :repoUrl "https://github.com/Sterlingg/json-snatcher.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (keycast
  :repoUrl "https://github.com/tarsius/keycast.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (latex-preview-pane
  :repoUrl "https://github.com/jsinglet/latex-preview-pane.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (link-hint.el
  :repoUrl "https://github.com/noctuid/link-hint.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (log4e
  :repoUrl "https://github.com/aki2o/log4e.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (loop.el
  :repoUrl "https://github.com/Wilfred/loop.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (lsp-mode
  :repoUrl "https://github.com/emacs-lsp/lsp-mode.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (lsp-pyright
  :repoUrl "https://github.com/emacs-lsp/lsp-pyright.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (lsp-ui
  :repoUrl "https://github.com/emacs-lsp/lsp-ui.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (macrostep
  :repoUrl "https://github.com/joddie/macrostep.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (magit
  :repoUrl "https://github.com/magit/magit.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (magit-gitflow
  :repoUrl "https://github.com/jtatarik/magit-gitflow.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (magit-popup
  :repoUrl "https://github.com/magit/magit-popup.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (magit-todos
  :repoUrl "https://github.com/alphapapa/magit-todos.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (marginalia
  :repoUrl "https://github.com/minad/marginalia.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (markdown-mode
  :repoUrl "https://github.com/jrblevin/markdown-mode.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (markdown-toc
  :repoUrl "https://github.com/ardumont/markdown-toc.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (math-symbol-lists
  :repoUrl "https://github.com/vspinu/math-symbol-lists.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (melpa
  :repoUrl "https://github.com/melpa/melpa.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (modern-cpp-font-lock
  :repoUrl "https://github.com/ludwigpacifici/modern-cpp-font-lock.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (multiple-cursors.el
  :repoUrl "https://github.com/magnars/multiple-cursors.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (multishell
  :repoUrl "https://github.com/emacs-straight/multishell.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (nodejs-repl.el
  :repoUrl "https://github.com/abicky/nodejs-repl.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (nose
  :repoUrl "https://github.com/emacsattic/nose.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (npm-mode
  :repoUrl "https://github.com/mojochao/npm-mode.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (ob-async
  :repoUrl "https://github.com/astahlman/ob-async.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (opencl-mode
  :repoUrl "https://github.com/salmanebah/opencl-mode.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (orderless
  :repoUrl "https://github.com/oantolin/orderless.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (org
  :repoUrl "https://github.com/emacs-straight/org.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (org-bullets
  :repoUrl "https://github.com/integral-dw/org-bullets.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (org-cliplink
  :repoUrl "https://github.com/rexim/org-cliplink.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (org-contrib
  :repoUrl "https://git.sr.ht/~bzg/org-contrib"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (org-gcal.el
  :repoUrl "https://github.com/kidd/org-gcal.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (orgit
  :repoUrl "https://github.com/magit/orgit.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (org-msg
  :repoUrl "https://github.com/jeremy-compostella/org-msg.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (org-recoll
  :repoUrl "https://github.com/alraban/org-recoll.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (org-ref
  :repoUrl "https://github.com/jkitchin/org-ref.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (org-yt
  :repoUrl "https://github.com/TobiasZawada/org-yt.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (ov
  :repoUrl "https://github.com/emacsorphanage/ov.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (overseer.el
  :repoUrl "https://github.com/tonini/overseer.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (ox-clip
  :repoUrl "https://github.com/jkitchin/ox-clip.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (ox-pandoc
  :repoUrl "https://github.com/emacsorphanage/ox-pandoc.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (package-lint
  :repoUrl "https://github.com/purcell/package-lint.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (parent-mode
  :repoUrl "https://github.com/Fanael/parent-mode.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (parsebib
  :repoUrl "https://github.com/joostkremers/parsebib.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (pcre2el
  :repoUrl "https://github.com/joddie/pcre2el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (persist
  :repoUrl "https://github.com/emacs-straight/persist.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (persp-mode.el
  :repoUrl "https://github.com/Bad-ptr/persp-mode.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (pipenv.el
  :repoUrl "https://github.com/pwalsh/pipenv.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (pip-requirements.el
  :repoUrl "https://github.com/Wilfred/pip-requirements.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (pkg-info
  :repoUrl "https://github.com/emacsorphanage/pkg-info.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (poetry.el
  :repoUrl "https://github.com/galaunay/poetry.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (polymode
  :repoUrl "https://github.com/polymode/polymode.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (poly-org
  :repoUrl "https://github.com/polymode/poly-org.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (popup-el
  :repoUrl "https://github.com/auto-complete/popup-el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (powerline
  :repoUrl "https://github.com/milkypostman/powerline.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (project
  :repoUrl "https://github.com/emacs-straight/project.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (projectile
  :repoUrl "https://github.com/bbatsov/projectile.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (pyimport
  :repoUrl "https://github.com/Wilfred/pyimport.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (py-isort.el
  :repoUrl "https://github.com/paetzke/py-isort.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (pythonic
  :repoUrl "https://github.com/pythonic-emacs/pythonic.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (pyvenv
  :repoUrl "https://github.com/jorgenschaefer/pyvenv.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (queue
  :repoUrl "https://github.com/emacs-straight/queue.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (quickrun
  :repoUrl "https://github.com/emacsorphanage/quickrun.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (rainbow-delimiters
  :repoUrl "https://github.com/Fanael/rainbow-delimiters.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (restart-emacs
  :repoUrl "https://github.com/iqbalansari/restart-emacs.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (rjsx-mode
  :repoUrl "https://github.com/felipeochoa/rjsx-mode.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (rtags
  :repoUrl "https://github.com/Andersbakken/rtags.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (s.el
  :repoUrl "https://github.com/magnars/s.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (shrink-path.el
  :repoUrl "https://gitlab.com/bennya/shrink-path.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (shut-up
  :repoUrl "https://github.com/cask/shut-up.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (skewer-mode
  :repoUrl "https://github.com/skeeto/skewer-mode.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (slime
  :repoUrl "https://github.com/slime/slime.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (smartparens
  :repoUrl "https://github.com/Fuco1/smartparens.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (spinner
  :repoUrl "https://github.com/emacs-straight/spinner.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (straight.el
  :repoUrl "https://github.com/raxod502/straight.el"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (string-inflection
  :repoUrl "https://github.com/akicho8/string-inflection.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (themes
  :repoUrl "https://github.com/doomemacs/themes.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (tide
  :repoUrl "https://github.com/ananthakumaran/tide.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (toc-org
  :repoUrl "https://github.com/snosov1/toc-org.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (transient
  :repoUrl "https://github.com/magit/transient.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (treepy.el
  :repoUrl "https://github.com/volrath/treepy.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (typescript.el
  :repoUrl "https://github.com/emacs-typescript/typescript.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (use-package
  :repoUrl "https://github.com/jwiegley/use-package.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (vertico
  :repoUrl "https://github.com/minad/vertico.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (vi-tilde-fringe
  :repoUrl "https://github.com/syl20bnr/vi-tilde-fringe.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (volatile-highlights.el
  :repoUrl "https://github.com/k-talo/volatile-highlights.el.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (with-editor
  :repoUrl "https://github.com/magit/with-editor.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (ws-butler
  :repoUrl "https://github.com/hlissner/ws-butler.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (xref
  :repoUrl "https://github.com/emacs-straight/xref.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (xref-js2
  :repoUrl "https://github.com/js-emacs/xref-js2.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
 (yasnippet
  :repoUrl "https://github.com/joaotavora/yasnippet.git"
  :commit "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"
 )
)
